@startuml
set separator none
title Short Term Lets Registration - Web Application - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Person(ServiceAdministrator, "Service Administrator", $descr="Manages registrations", $tags="", $link="")
Person(Owner, "Owner", $descr="Owns and runs a short-term let", $tags="", $link="")
Person(LocalAuthorityOfficer, "Local Authority Officer", $descr="Uses register to solve problems in local area", $tags="", $link="")
System(GOVUKPay, "GOV.UK Pay", $descr="Allows users to make payments", $tags="", $link="")
System(OneLogin, "One Login", $descr="Let's users sign in", $tags="", $link="")
System(GOVUKNotify, "GOV.UK Notify", $descr="Sends users notifications", $tags="", $link="")
System(AuthenticationProvider, "Authentication Provider", $descr="Sign in for administrator's users", $tags="", $link="")
System(OSPlacesAPI, "OS Places API", $descr="Identifies UK Addresses", $tags="", $link="")
ContainerDb(ShortTermLetsRegistration.STLRegister, "STL Register", $techn="Postgres", $descr="Register of short term lets", $tags="", $link="")
ContainerDb(ShortTermLetsRegistration.FileStore, "File Store", $techn="Cloud Storage", $descr="Storage for compliance documents", $tags="", $link="")

Container_Boundary("ShortTermLetsRegistration.WebApplication_boundary", "Web Application", $tags="") {
  Component(ShortTermLetsRegistration.WebApplication.OperatorRegistration, "Operator Registration", $techn="", $descr="Flow for registering and renewing registration of short-term let", $tags="", $link="")
  Component(ShortTermLetsRegistration.WebApplication.RegisterView, "Register View", $techn="", $descr="View of register for approved groups", $tags="", $link="")
  Component(ShortTermLetsRegistration.WebApplication.InternalService, "Internal Service", $techn="", $descr="Service to provide administrator access to complete registration tasks.", $tags="", $link="")
  Component(ShortTermLetsRegistration.WebApplication.Dataview, "Data view", $techn="", $descr="Aggregated data from register", $tags="", $link="")
  Component(ShortTermLetsRegistration.WebApplication.RegisterAdapter, "Register Adapter", $techn="", $descr="Wrapper around register database", $tags="", $link="")
}

Rel(Owner, ShortTermLetsRegistration.WebApplication.OperatorRegistration, "Registers a short term let", $techn="HTTPS", $tags="", $link="")
Rel(ServiceAdministrator, ShortTermLetsRegistration.WebApplication.InternalService, "Resolve queries about registrations", $techn="HTTPS", $tags="", $link="")
Rel(LocalAuthorityOfficer, ShortTermLetsRegistration.WebApplication.RegisterView, "Finds contact details from register", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.RegisterAdapter, ShortTermLetsRegistration.STLRegister, "Store short term let data", $techn="TCP/SQL", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.OperatorRegistration, GOVUKPay, "User makes a payment", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.OperatorRegistration, OneLogin, "User signs into service", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.RegisterView, OneLogin, "User signs into service", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.InternalService, AuthenticationProvider, "Admin users sign into service", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.OperatorRegistration, GOVUKNotify, "Notify user of completed application", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.RegisterAdapter, ShortTermLetsRegistration.FileStore, "Upload/review compliance documents", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.OperatorRegistration, OSPlacesAPI, "Request addresses at postcode", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.OperatorRegistration, ShortTermLetsRegistration.WebApplication.RegisterAdapter, "Add or update registration", $techn="", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.RegisterView, ShortTermLetsRegistration.WebApplication.RegisterAdapter, "Retrieve information about registration", $techn="", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.InternalService, ShortTermLetsRegistration.WebApplication.RegisterAdapter, "Manage registration", $techn="", $tags="", $link="")
Rel(ShortTermLetsRegistration.WebApplication.Dataview, ShortTermLetsRegistration.WebApplication.RegisterAdapter, "Retrieve data about registrations", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml