@startuml
set separator none
title Short Term Lets Registration - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("Local Authority", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
Boundary(group_1, "Local Authority", $tags="Local Authority") {
  Person(Planner, "Planner", $descr="Plans housing schemes in Local Authority area", $tags="", $link="")
  Person(Officer, "Officer", $descr="Uses register to solve problems in local area", $tags="", $link="")
}

AddBoundaryTag("Short Term Lets Service", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
Boundary(group_2, "Short Term Lets Service", $tags="Short Term Lets Service") {
  System(ShortTermLetsRegistration, "Short Term Lets Registration", $descr="Platform for registering, and querying short term lets", $tags="", $link="")
}

AddBoundaryTag("VisitEngland", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
Boundary(group_3, "VisitEngland", $tags="VisitEngland") {
  System(VisitEnglandDataLake, "Visit England Data Lake", $descr="", $tags="", $link="")
  System(VisitorReady, "Visitor Ready", $descr="Entry level quality scheme", $tags="", $link="")
}

Person(Administrator, "Administrator", $descr="Manages registrations", $tags="", $link="")
System(GOVUKNotify, "GOV.UK Notify", $descr="Sends users notifications", $tags="", $link="")
System(AuthenticationProvider, "Authentication Provider", $descr="Sign in for administrator's users", $tags="", $link="")
System(OSPlacesAPI, "OS Places API", $descr="Identifies UK Addresses", $tags="", $link="")
Person(Operator, "Operator", $descr="Owns and runs a short term let", $tags="", $link="")
Person(ManagementCompany, "Management Company", $descr="", $tags="", $link="")
System(BookingPlatform, "Booking Platform", $descr="Lists short term lets and facilitates bookings", $tags="", $link="")
System(PolicyMakers, "Policy Makers", $descr="", $tags="", $link="")
System(GOVUKPay, "GOV.UK Pay", $descr="Allows users to make payments", $tags="", $link="")
System(OneLogin, "One Login", $descr="Let's users sign in", $tags="", $link="")

Rel(Operator, ManagementCompany, "Hire to manage short term let", $techn="", $tags="", $link="")
Rel(Operator, BookingPlatform, "Lists STL on platform", $techn="", $tags="", $link="")
Rel(ManagementCompany, ShortTermLetsRegistration, "Register short term lets on behalf of operator", $techn="", $tags="", $link="")
Rel(ManagementCompany, BookingPlatform, "Lists short term let on platform", $techn="", $tags="", $link="")
Rel(BookingPlatform, ShortTermLetsRegistration, "Verify registration of short term let", $techn="", $tags="", $link="")
Rel(Planner, ShortTermLetsRegistration, "Retrieve data on short term lets", $techn="", $tags="", $link="")
Rel(ShortTermLetsRegistration, VisitorReady, "Optionally enrol operators", $techn="", $tags="", $link="")
Rel(ShortTermLetsRegistration, VisitEnglandDataLake, "Supply data on registration", $techn="", $tags="", $link="")
Rel(PolicyMakers, ShortTermLetsRegistration, "Retrieve data on short term lets", $techn="", $tags="", $link="")
Rel(Operator, ShortTermLetsRegistration, "Registers a short term let", $techn="HTTPS", $tags="", $link="")
Rel(Administrator, ShortTermLetsRegistration, "Resolve queries about registrations", $techn="HTTPS", $tags="", $link="")
Rel(Officer, ShortTermLetsRegistration, "Finds contact details from register", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, GOVUKPay, "User makes a payment", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, OneLogin, "User signs into service", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, AuthenticationProvider, "Admin users sign into service", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, GOVUKNotify, "Notify user of completed application", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, OSPlacesAPI, "Request addresses at postcode", $techn="HTTPS", $tags="", $link="")

SHOW_LEGEND(true)
@enduml