@startuml
set separator none
title Short Term Lets Registration - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("Local Authority", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
Boundary(group_1, "Local Authority", $tags="Local Authority") {
  Person(LocalAuthorityPlanner, "Local Authority Planner", $descr="Plans housing schemes in Local Authority area", $tags="", $link="")
  Person(LocalAuthorityOfficer, "Local Authority Officer", $descr="Uses register to solve problems in local area", $tags="", $link="")
}

AddBoundaryTag("Short Term Lets Service", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
Boundary(group_2, "Short Term Lets Service", $tags="Short Term Lets Service") {
  System(ShortTermLetsRegistration, "Short Term Lets Registration", $descr="Platform for registering, and querying short term lets", $tags="", $link="")
}

Person(ServiceAdministrator, "Service Administrator", $descr="Manages registrations", $tags="", $link="")
System(GOVUKNotify, "GOV.UK Notify", $descr="Sends users notifications", $tags="", $link="")
System(AuthenticationProvider, "Authentication Provider", $descr="Sign in for administrator's users", $tags="", $link="")
System(OSPlacesAPI, "OS Places API", $descr="Identifies UK Addresses", $tags="", $link="")
Person(Owner, "Owner", $descr="Owns and runs a short-term let", $tags="", $link="")
Person(Agent, "Agent", $descr="Runs a short-term let on an owner's behalf", $tags="", $link="")
System(BookingPlatform, "Booking Platform", $descr="Lists short term lets and facilitates bookings", $tags="", $link="")
System(PolicyMakers, "Policy Makers", $descr="", $tags="", $link="")
System(GOVUKPay, "GOV.UK Pay", $descr="Allows users to make payments", $tags="", $link="")
System(OneLogin, "One Login", $descr="Sign in for external and Local Authority users", $tags="", $link="")

Rel(Owner, Agent, "Hire to manage short term let", $techn="", $tags="", $link="")
Rel(Owner, BookingPlatform, "Lists STL on platform", $techn="", $tags="", $link="")
Rel(Agent, ShortTermLetsRegistration, "Register short term lets on behalf of operator", $techn="", $tags="", $link="")
Rel(Agent, BookingPlatform, "Lists short term let on platform", $techn="", $tags="", $link="")
Rel(BookingPlatform, ShortTermLetsRegistration, "Verify registration of short term let", $techn="", $tags="", $link="")
Rel(LocalAuthorityPlanner, ShortTermLetsRegistration, "Retrieve data on short term lets", $techn="", $tags="", $link="")
Rel(PolicyMakers, ShortTermLetsRegistration, "Retrieve data on short term lets", $techn="", $tags="", $link="")
Rel(Owner, ShortTermLetsRegistration, "Registers a short term let", $techn="HTTPS", $tags="", $link="")
Rel(ServiceAdministrator, ShortTermLetsRegistration, "Resolve queries about registrations", $techn="HTTPS", $tags="", $link="")
Rel(LocalAuthorityOfficer, ShortTermLetsRegistration, "Finds contact details from register", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, GOVUKPay, "User makes a payment", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, OneLogin, "User signs into service", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, AuthenticationProvider, "Admin users sign into service", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, GOVUKNotify, "Notify user of completed application", $techn="HTTPS", $tags="", $link="")
Rel(ShortTermLetsRegistration, OSPlacesAPI, "Request addresses at postcode", $techn="HTTPS", $tags="", $link="")

SHOW_LEGEND(true)
@enduml